package:
  name: arm-variant
  version: 1.1.0

build:
  number: 1
  noarch: generic
  string: "{{ arm_variant_type }}"
  track_features:
    - arm_{{ arm_variant_type }}  # [arm_variant_type != arm_variant_type_default]

test:
  commands:
    - exit 0

about:
  home: https://github.com/conda-forge/arm-variant-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A meta-package to select the ARM variant.'
  description: |
    Use this package to select which ARM variant to use at runtime or compile for.

    There are a couple of ARM variants that differ based on architecture.

    Currently the main ones are:
      * SBSA ( Server Base System Architecture ), which is used in clusters, cloud environments, etc.
      * Tegra ( System on a Chip ), which is used in edge applications like mobile internet devices, streaming systems, etc.

    These variants have different CUDA Toolkits, and the arm-variant package is used to select between them.

    The default is SBSA. Select the tegra 'arm-variant' package by installing 'arm-variant=*=tegra'.

extra:
  recipe-maintainers:
    - jakirkham
